---
version: 2
multicolumn: false
web-width: 500px
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/precision_map1/precision_map1.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/236765/articles/306641/master/file/figures/precision_map1/precision_map1.png"
