---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/r_u5/r_u5.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/236765/articles/306641/master/folder/figures/r_u5"
    url: "/users/236765/articles/306641/master/file/figures/r_u5/r_u5.png"
