---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/b_Fch4_U1S04_byS_Stor/b_Fch4_U1S04_byS_Stor.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    folder_url: "/users/236765/articles/306641/master/folder/figures/b_Fch4_U1S04_byS_Stor"
    url: "/users/236765/articles/306641/master/file/figures/b_Fch4_U1S04_byS_Stor/b_Fch4_U1S04_byS_Stor.png"
