---
version: 2
multicolumn: false
web-width: 500
align: center
float: h!
grid:
  rows: 1
  columns: 1
  grid_elements:
  - path: figures/fp_on_map_Stordalen/default_figure.png
    type: static
    from:
    - 1
    - 1
    to:
    - 1
    - 1
    url: "/users/236765/articles/306641/master/file/figures/fp_on_map_Stordalen/default_figure.png"
    folder_url: "/users/236765/articles/306641/master/folder/figures/fp_on_map_Stordalen"
